# Generated by Django 3.0.3 on 2020-03-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('limit_semester', models.IntegerField()),
                ('limit_subject', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('student_name', models.TextField()),
                ('student_semester', models.IntegerField()),
                ('student_emial', models.EmailField(default=True, max_length=254)),
                ('student_password', models.CharField(default=True, max_length=30)),
                ('student_approve', models.BooleanField(default=False)),
                ('student_voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('subject_name', models.TextField()),
                ('subject_semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('student_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='SSV.Student')),
                ('subject_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='SSV.Subject')),
            ],
        ),
    ]
