# Generated by Django 3.0.3 on 2020-03-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSV', '0002_student_student_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voted',
            name='student_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='SSV.Student'),
        ),
        migrations.AlterField(
            model_name='voted',
            name='subject_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='SSV.Subject'),
        ),
    ]
