# Generated by Django 3.0.3 on 2020-03-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSV', '0006_auto_20200329_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_college_id',
            field=models.CharField(default=False, max_length=10, unique=True),
        ),
    ]
