# Generated by Django 3.0.3 on 2020-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSV', '0007_auto_20200329_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_college_id',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
