# Generated by Django 3.0.3 on 2020-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSV', '0009_auto_20200329_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
